# Site
repository: pbernstein/pbernstein.github.io
# favicon: images/favicon.ico

# Personal info
name: Peter Bernstein
title: Senior Application Architect 
email: pbernstein@gmail.com
website: https://pbernstein.github.io/

# Social links
github_username:  pbernstein
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: peter-bernstein-9aa18a2
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/headShot.JPG
about_content: | # this will include new lines to allow paragraphs
  Hello, my name's Peter. I'm a senior application architect. I have experience writing large data processing systems, writing web apps, administering systems, and working with people all over the world. 

  I am most skilled in: Working with data, massive amounts of data. Also, front ends and tooling, but mostly big backend systems. 

# Experience Section
# experience_title: Experience

# Personal Projects Section
projects_title: Personal Projects

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my passion for solving problems with software, some of my other interests and hobbies are:
   - Going on adventures with my kids 
   - Brazilian Jiu Jitsu 
   - Coffee
   - Mechanical Keyboards
   - Piano, guitar, and meditation


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
